[general]
import = ["alabaster_dark.toml"]

[font]
size = 10.0

[font.bold]
family = "InconsolataGo Nerd Font"

[font.bold_italic]
family = "InconsolataGo Nerd Font"

[font.italic]
family = "InconsolataGo Nerd Font"

[font.normal]
family = "InconsolataGo Nerd Font"
