[general]
import = ["alabaster_dark.toml"]

[font]
size = 12.0

[font.bold]
family = "Inconsolata LGC Nerd Font"

[font.bold_italic]
family = "Inconsolata LGC Nerd Font"

[font.italic]
family = "Inconsolata LGC Nerd Font"

[font.normal]
family = "Inconsolata LGC Nerd Font"
